# Generated by Django 3.1.4 on 2021-03-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangochat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isanswer',
            field=models.BooleanField(default=False),
        ),
    ]
