# Generated by Django 3.1.4 on 2021-04-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangochat', '0004_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.AddField(
            model_name='message',
            name='isimage',
            field=models.BooleanField(default=False),
        ),
    ]
